
// Generated by Cadence Genus(TM) Synthesis Solution 19.13-s073_1
// Generated on: Mar 14 2023 15:01:36 +07 (Mar 14 2023 08:01:36 UTC)

// Verification Directory fv/bound_flasher 

module bound_flasher(clock, reset, flick, led);
  input clock, reset, flick;
  output [15:0] led;
  wire clock, reset, flick;
  wire [15:0] led;
  wire [3:0] counter;
  wire [2:0] state;
  wire n_1, n_2, n_3, n_4, n_8, n_9, n_10, n_11;
  wire n_12, n_13, n_14, n_15, n_16, n_17, n_18, n_19;
  wire n_20, n_21, n_22, n_23, n_24, n_25, n_26, n_27;
  wire n_28, n_30, n_31, n_32, n_33, n_34, n_35, n_36;
  wire n_37, n_38, n_39, n_40, n_41, n_42, n_43, n_44;
  wire n_45, n_46, n_47, n_48, n_49, n_50, n_51, n_52;
  wire n_53, n_54, n_55, n_56, n_57, n_58, n_59, n_60;
  wire n_61, n_62, n_63, n_64, n_65, n_66, n_67, n_68;
  wire n_70, n_71, n_72, n_73, n_74, n_75, n_76, n_77;
  wire n_78, n_79, n_80, n_81, n_82, n_83, n_84, n_85;
  wire n_86, n_87, n_88, n_89, n_90, n_91, n_92, n_93;
  wire n_94, n_95, n_96, n_97, n_98, n_99, n_100, n_101;
  wire n_102, n_103, n_104, n_105, n_106, n_107, n_108, n_109;
  wire n_110, n_111, n_112, n_113, n_114, n_115, n_116, n_117;
  wire n_118, n_119, n_120, n_121, n_122, n_123, n_124, n_125;
  wire n_126, n_127, n_128, n_129, n_130, n_131, n_135;
  OAI211X1 g5713__2398(.A0 (counter[2]), .A1 (n_54), .B0 (n_127), .C0
       (n_61), .Y (n_131));
  DFFRHQX1 \led_reg[2] (.RN (reset), .CK (clock), .D (n_128), .Q
       (led[2]));
  DFFRX1 \counter_reg[2] (.RN (reset), .CK (clock), .D (n_126), .Q
       (n_24), .QN (counter[2]));
  DFFRHQX1 \led_reg[8] (.RN (reset), .CK (clock), .D (n_123), .Q
       (led[8]));
  DFFRHQX1 \led_reg[10] (.RN (reset), .CK (clock), .D (n_125), .Q
       (led[10]));
  OAI221X1 g5712__5107(.A0 (counter[1]), .A1 (n_63), .B0 (counter[0]),
       .B1 (n_76), .C0 (n_110), .Y (n_130));
  DFFRHQX1 \led_reg[11] (.RN (reset), .CK (clock), .D (n_108), .Q
       (led[11]));
  DFFRHQX1 \led_reg[14] (.RN (reset), .CK (clock), .D (n_104), .Q
       (led[14]));
  DFFRHQX1 \led_reg[3] (.RN (reset), .CK (clock), .D (n_121), .Q
       (led[3]));
  DFFRHQX1 \led_reg[9] (.RN (reset), .CK (clock), .D (n_109), .Q
       (led[9]));
  DFFRHQX1 \led_reg[15] (.RN (reset), .CK (clock), .D (n_103), .Q
       (led[15]));
  OAI211X1 g5715__6260(.A0 (counter[0]), .A1 (n_101), .B0 (n_96), .C0
       (n_50), .Y (n_129));
  DFFRHQX1 \led_reg[7] (.RN (reset), .CK (clock), .D (n_117), .Q
       (led[7]));
  DFFRHQX1 \led_reg[6] (.RN (reset), .CK (clock), .D (n_106), .Q
       (led[6]));
  DFFRHQX1 \led_reg[13] (.RN (reset), .CK (clock), .D (n_105), .Q
       (led[13]));
  DFFRHQX1 \led_reg[1] (.RN (reset), .CK (clock), .D (n_119), .Q
       (led[1]));
  DFFRHQX1 \led_reg[12] (.RN (reset), .CK (clock), .D (n_113), .Q
       (led[12]));
  DFFRHQX1 \led_reg[4] (.RN (reset), .CK (clock), .D (n_115), .Q
       (led[4]));
  OAI2BB1X1 g5740__4319(.A0N (n_120), .A1N (n_124), .B0 (n_95), .Y
       (n_128));
  AOI221X1 g5726__8428(.A0 (counter[2]), .A1 (n_39), .B0 (n_91), .B1
       (flick), .C0 (n_66), .Y (n_127));
  OAI221X1 g5729__5526(.A0 (n_92), .A1 (n_19), .B0 (n_89), .B1 (n_42),
       .C0 (n_94), .Y (n_126));
  OAI2BB1X1 g5748__6783(.A0N (n_107), .A1N (n_124), .B0 (n_100), .Y
       (n_125));
  OAI2BB1X1 g5746__3680(.A0N (n_112), .A1N (n_124), .B0 (n_99), .Y
       (n_123));
  OAI211X1 g5754__1617(.A0 (n_3), .A1 (n_48), .B0 (n_68), .C0 (n_116),
       .Y (n_122));
  OAI2BB1X1 g5741__2802(.A0N (n_120), .A1N (n_118), .B0 (n_80), .Y
       (n_121));
  OAI2BB1X1 g5739__1705(.A0N (n_114), .A1N (n_118), .B0 (n_86), .Y
       (n_119));
  NAND2X1 g5737__5122(.A (n_116), .B (n_93), .Y (n_117));
  OAI2BB1X1 g5736__8246(.A0N (n_114), .A1N (n_111), .B0 (n_90), .Y
       (n_115));
  DFFRHQX1 \state_reg[2] (.RN (reset), .CK (clock), .D (n_74), .Q
       (state[2]));
  DFFRHQX1 \led_reg[0] (.RN (reset), .CK (clock), .D (n_81), .Q
       (led[0]));
  DFFRHQX1 \led_reg[5] (.RN (reset), .CK (clock), .D (n_71), .Q
       (led[5]));
  OAI2BB1X1 g5750__7098(.A0N (n_112), .A1N (n_111), .B0 (n_73), .Y
       (n_113));
  AOI221X1 g5727__6131(.A0 (state[2]), .A1 (n_58), .B0 (counter[0]),
       .B1 (n_62), .C0 (n_36), .Y (n_110));
  OAI2BB1X1 g5747__1881(.A0N (n_112), .A1N (n_118), .B0 (n_84), .Y
       (n_109));
  OAI2BB1X1 g5749__5115(.A0N (n_107), .A1N (n_118), .B0 (n_82), .Y
       (n_108));
  OAI2BB1X1 g5742__7482(.A0N (n_120), .A1N (n_111), .B0 (n_88), .Y
       (n_106));
  OAI2BB1X1 g5751__4733(.A0N (n_112), .A1N (n_102), .B0 (n_67), .Y
       (n_105));
  OAI2BB1X1 g5752__6161(.A0N (n_107), .A1N (n_111), .B0 (n_79), .Y
       (n_104));
  OAI2BB1X1 g5753__9315(.A0N (n_107), .A1N (n_102), .B0 (n_77), .Y
       (n_103));
  NOR2X1 g5757__9945(.A (n_60), .B (n_15), .Y (n_101));
  OAI2BB1X1 g5758__2883(.A0N (n_98), .A1N (n_43), .B0 (led[10]), .Y
       (n_100));
  OAI2BB1X1 g5759__2346(.A0N (n_98), .A1N (n_44), .B0 (led[8]), .Y
       (n_99));
  OAI211X1 g5728__1666(.A0 (n_53), .A1 (n_135), .B0 (n_59), .C0 (n_14),
       .Y (n_97));
  AOI221X1 g5738__7410(.A0 (counter[0]), .A1 (n_38), .B0 (n_37), .B1
       (n_46), .C0 (n_27), .Y (n_96));
  OAI2BB1X1 g5760__6417(.A0N (n_98), .A1N (n_45), .B0 (led[2]), .Y
       (n_95));
  AOI22X1 g5755__5477(.A0 (n_98), .A1 (n_75), .B0 (counter[1]), .B1
       (n_118), .Y (n_94));
  OAI21X1 g5765__2398(.A0 (n_92), .A1 (n_87), .B0 (led[7]), .Y (n_93));
  NOR2X1 g5762__5107(.A (state[1]), .B (n_47), .Y (n_91));
  OAI21X1 g5763__6260(.A0 (n_89), .A1 (n_85), .B0 (led[4]), .Y (n_90));
  OAI21X1 g5764__4319(.A0 (n_89), .A1 (n_87), .B0 (led[6]), .Y (n_88));
  OAI21X1 g5761__8428(.A0 (n_83), .A1 (n_85), .B0 (led[1]), .Y (n_86));
  OAI21X1 g5766__5526(.A0 (n_83), .A1 (n_72), .B0 (led[9]), .Y (n_84));
  OAI21X1 g5767__6783(.A0 (n_83), .A1 (n_78), .B0 (led[11]), .Y (n_82));
  OAI21X1 g5768__3680(.A0 (n_70), .A1 (n_65), .B0 (n_51), .Y (n_81));
  OAI21X1 g5756__1617(.A0 (n_83), .A1 (n_87), .B0 (led[3]), .Y (n_80));
  OAI21X1 g5770__2802(.A0 (n_89), .A1 (n_78), .B0 (led[14]), .Y (n_79));
  OAI21X1 g5771__1705(.A0 (n_92), .A1 (n_78), .B0 (led[15]), .Y (n_77));
  AOI21X1 g5772__5122(.A0 (counter[1]), .A1 (n_55), .B0 (n_75), .Y
       (n_76));
  OAI211X1 g5773__8246(.A0 (n_12), .A1 (n_35), .B0 (n_64), .C0 (n_30),
       .Y (n_74));
  OAI21X1 g5774__7098(.A0 (n_89), .A1 (n_72), .B0 (led[12]), .Y (n_73));
  OAI21X1 g5775__6131(.A0 (n_70), .A1 (n_135), .B0 (n_56), .Y (n_71));
  AOI221X1 g5789__1881(.A0 (n_24), .A1 (n_112), .B0 (counter[2]), .B1
       (n_107), .C0 (n_31), .Y (n_68));
  OAI21X1 g5769__5115(.A0 (n_92), .A1 (n_72), .B0 (led[13]), .Y (n_67));
  OAI221X1 g5777__7482(.A0 (n_32), .A1 (n_65), .B0 (n_64), .B1 (n_135),
       .C0 (n_16), .Y (n_66));
  AOI22X1 g5778__4733(.A0 (counter[0]), .A1 (n_52), .B0 (n_4), .B1
       (n_10), .Y (n_63));
  OAI2BB1X1 g5779__6161(.A0N (counter[1]), .A1N (n_70), .B0 (n_41), .Y
       (n_62));
  NAND3X1 g5781__9315(.A (n_49), .B (state[0]), .C (n_25), .Y (n_61));
  NAND2BX1 g5791__9945(.AN (n_57), .B (n_34), .Y (n_60));
  AOI221X1 g5776__2883(.A0 (n_58), .A1 (n_40), .B0 (n_13), .B1 (n_11),
       .C0 (n_57), .Y (n_59));
  OAI21X1 g5780__2346(.A0 (n_55), .A1 (n_135), .B0 (led[5]), .Y (n_56));
  AOI2BB1X1 g5784__1666(.A0N (n_114), .A1N (n_53), .B0 (n_52), .Y
       (n_54));
  OAI21X1 g5785__7410(.A0 (n_65), .A1 (n_55), .B0 (led[0]), .Y (n_51));
  OR4X1 g5790__6417(.A (n_49), .B (n_28), .C (n_135), .D (n_20), .Y
       (n_50));
  NOR2X1 g5786__5477(.A (state[0]), .B (n_22), .Y (n_75));
  AOI21X1 g5792__2398(.A0 (counter[2]), .A1 (n_55), .B0 (n_17), .Y
       (n_48));
  MX2X1 g5794__5107(.A (state[0]), .B (state[2]), .S0 (n_135), .Y
       (n_47));
  MXI2XL g5795__6260(.A (n_89), .B (n_135), .S0 (n_49), .Y (n_46));
  INVX1 g5796(.A (n_87), .Y (n_45));
  INVX1 g5797(.A (n_72), .Y (n_44));
  INVX1 g5798(.A (n_78), .Y (n_43));
  NOR2X1 g5799__4319(.A (counter[1]), .B (n_55), .Y (n_42));
  AOI22X1 g5793__8428(.A0 (n_18), .A1 (n_40), .B0 (n_112), .B1 (n_21),
       .Y (n_41));
  OAI22X1 g5788__5526(.A0 (counter[1]), .A1 (n_70), .B0 (counter[3]),
       .B1 (n_53), .Y (n_39));
  OAI22X1 g5819__6783(.A0 (state[0]), .A1 (n_9), .B0 (n_49), .B1
       (n_37), .Y (n_38));
  NAND2BX1 g5801__3680(.AN (n_55), .B (n_114), .Y (n_85));
  OR2X1 g5804__1617(.A (n_33), .B (n_55), .Y (n_87));
  OR2X1 g5805__2802(.A (n_23), .B (n_55), .Y (n_72));
  NOR3X1 g5816__1705(.A (counter[1]), .B (n_83), .C (n_53), .Y (n_36));
  INVX1 g5809(.A (n_52), .Y (n_35));
  OA22X1 g5810__5122(.A0 (n_33), .A1 (n_32), .B0 (n_1), .B1 (n_53), .Y
       (n_34));
  NOR3X1 g5813__8246(.A (state[0]), .B (n_64), .C (n_65), .Y (n_31));
  NAND3X1 g5814__7098(.A (state[2]), .B (n_28), .C (n_65), .Y (n_30));
  NOR3BX1 g5815__6131(.AN (n_40), .B (counter[2]), .C (n_26), .Y
       (n_27));
  OR2X1 g5806__1881(.A (n_26), .B (n_55), .Y (n_78));
  OAI211X1 g5817__5115(.A0 (n_24), .A1 (flick), .B0 (n_23), .C0 (n_33),
       .Y (n_25));
  OA22X1 g5818__7482(.A0 (counter[1]), .A1 (n_64), .B0 (n_49), .B1
       (n_23), .Y (n_22));
  AND3XL g5820__4733(.A (state[1]), .B (n_21), .C (n_20), .Y (n_52));
  AOI211XL g5800__6161(.A0 (counter[3]), .A1 (state[2]), .B0 (n_18),
       .C0 (n_70), .Y (n_19));
  OAI211X1 g5812__9315(.A0 (counter[2]), .A1 (n_21), .B0 (n_83), .C0
       (n_89), .Y (n_17));
  NOR2X1 g5782__9945(.A (n_111), .B (n_118), .Y (n_16));
  NAND2X1 g5787__2883(.A (n_120), .B (n_102), .Y (n_116));
  OR2XL g5824__1666(.A (state[0]), .B (n_8), .Y (n_55));
  AOI31X1 g5783__7410(.A0 (state[0]), .A1 (n_107), .A2 (flick), .B0
       (n_64), .Y (n_15));
  AO21X1 g5811__6417(.A0 (n_107), .A1 (n_20), .B0 (n_32), .Y (n_14));
  NOR2X1 g5803__5477(.A (n_13), .B (n_70), .Y (n_124));
  NAND2X1 g5825__2398(.A (n_98), .B (n_107), .Y (n_12));
  AND2X1 g5821__5107(.A (state[1]), .B (n_37), .Y (n_11));
  NOR2BX1 g5826__6260(.AN (n_10), .B (n_114), .Y (n_57));
  NOR2X1 g5822__4319(.A (state[1]), .B (n_37), .Y (n_40));
  NAND2X1 g5823__8428(.A (n_114), .B (n_98), .Y (n_65));
  INVX1 g5842(.A (n_8), .Y (n_9));
  NOR2X1 g5827__5526(.A (n_92), .B (n_26), .Y (n_58));
  NOR2X1 g5802__6783(.A (n_92), .B (n_70), .Y (n_102));
  NOR2X1 g5807__3680(.A (n_89), .B (n_70), .Y (n_111));
  INVX1 g5844(.A (n_21), .Y (n_53));
  NOR2X1 g5808__1617(.A (n_83), .B (n_70), .Y (n_118));
  OR2X1 g5835__2802(.A (state[2]), .B (n_49), .Y (n_32));
  INVX1 g5832(.A (n_112), .Y (n_23));
  NAND2X1 g5849__1705(.A (state[2]), .B (n_49), .Y (n_64));
  INVX1 g5831(.A (n_98), .Y (n_13));
  NOR2X1 g5846__5122(.A (state[2]), .B (state[1]), .Y (n_8));
  INVX1 g5843(.A (n_33), .Y (n_120));
  INVX1 g5833(.A (n_89), .Y (n_4));
  INVX1 g5834(.A (n_107), .Y (n_26));
  AND2XL g5836__7098(.A (n_3), .B (n_18), .Y (n_114));
  OR2XL g5837__6131(.A (n_24), .B (n_2), .Y (n_83));
  OR2X1 g5850__1881(.A (n_2), .B (counter[2]), .Y (n_92));
  AO21X1 g5829__5115(.A0 (state[1]), .A1 (state[2]), .B0 (n_28), .Y
       (n_70));
  NOR2X1 g5845__7482(.A (n_18), .B (n_49), .Y (n_1));
  NOR2X1 g5847__4733(.A (n_49), .B (state[0]), .Y (n_10));
  OR2X1 g5851__6161(.A (counter[3]), .B (n_18), .Y (n_33));
  NAND2X1 g5848__9315(.A (state[2]), .B (state[0]), .Y (n_37));
  AND2XL g5838__9945(.A (counter[2]), .B (n_2), .Y (n_98));
  AND2XL g5839__2883(.A (counter[3]), .B (n_18), .Y (n_112));
  AND2XL g5841__2346(.A (counter[3]), .B (counter[1]), .Y (n_107));
  OR2XL g5840__1666(.A (counter[0]), .B (counter[2]), .Y (n_89));
  INVX1 g5853(.A (flick), .Y (n_20));
  DFFRX1 \counter_reg[0] (.RN (reset), .CK (clock), .D (n_129), .Q
       (counter[0]), .QN (n_2));
  DFFRX1 \state_reg[0] (.RN (reset), .CK (clock), .D (n_131), .Q
       (state[0]), .QN (n_28));
  DFFRX1 \counter_reg[1] (.RN (reset), .CK (clock), .D (n_130), .Q
       (counter[1]), .QN (n_18));
  DFFRX1 \state_reg[1] (.RN (reset), .CK (clock), .D (n_97), .Q
       (state[1]), .QN (n_49));
  DFFRX1 \counter_reg[3] (.RN (reset), .CK (clock), .D (n_122), .Q
       (counter[3]), .QN (n_3));
  NAND2BX1 g5898(.AN (n_92), .B (n_114), .Y (n_135));
  NOR2X1 g5852__5900(.A (state[2]), .B (n_28), .Y (n_21));
endmodule

